### ISSUE TITLE
double image

### ISSUE THREAD

**Issue by LinQinLiang** [wkim97/ADA#2]
Hello, a nice work, i want to know why you use a 'doube image' in the code, may be some other reasons i don't know, thank you for attention
<img width="421" alt="b8ba74a72fee3ee2deacd2d6186bb2c" src="https://user-images.githubusercontent.com/45589968/207380093-6c8cda0c-5b7c-40cd-bf4a-b713e580d080.png">

**Comment by wkim97** [comment]
Hi LinQinLiang.
Thank you for your interest on our work!

To compute the diversity loss in our paper, we concatenate the input "image" and pass it into our attack generator.
We named that with "double_image" to represent that it's simply "doubly" concatenated result of input "image".

This implementation is similar to that of DSGAN, which originally proposed the diversity-sensitive regularization (https://github.com/maga33/DSGAN/blob/c96f928a4c03ac15dd9ac71fb3fcaa948400d7b5/Inpainting/train.py#L173).

Best regards,
Woo Jae
